mongodb_uri: mongodb://mongo_db:27017/turg_db
max_x: 5000
max_y: 5000
max_z: 100
ping_interval: 20
rate_limit: 60
max_range: 100
api_key: 0cbf88f3-a487-4b9c-8e56-33defd257a26
service_account: '{
	"type": "service_account",
	"project_id": "project_id",
	"private_key_id": "private_key_id",
	"private_key": "private_key",
	"client_email": "client_email",
	"client_id": "client_id",
	"auth_uri": "auth_uri",
	"token_uri": "token_uri",
	"auth_provider_x509_cert_url": "auth_provider_x509_cert_url",
	"client_x509_cert_url": "client_x509_cert_url"
}'
jwt_certs_url: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com